// Hardcoded admin credentials
const adminCredentials = {
    userId: 'admin',
        password: 'admin123'
        };

        // Login Handler
        document.getElementById('loginForm').addEventListener('submit', function (e) {
            e.preventDefault();

                const userType = document.getElementById('userType').value;
                    const userId = document.getElementById('userId').value;
                        const password = document.getElementById('password').value;

                            if (userType === 'admin') {
                                    if (userId === adminCredentials.userId && password === adminCredentials.password) {
                                                window.location.href = 'admin.html';
                                                        } else {
                                                                    alert('Invalid Admin Credentials');
                                                                            }
                                                                                } else if (userType === 'underwriter') {
                                                                                        const underwriters = JSON.parse(localStorage.getItem('underwriters')) || [];
                                                                                                const underwriter = underwriters.find(u => u.userId === userId && u.password === password);
                                                                                                        if (underwriter) {
                                                                                                                    window.location.href = 'underwriter.html';
                                                                                                                            } else {
                                                                                                                                        alert('Invalid Underwriter Credentials');
                                                                                                                                                }
                                                                                                                                                    }
                                                                                                                                                    });

                                                                                                                                                    // Utility to navigate admin pages
                                                                                                                                                    function navigateTo(page) {
                                                                                                                                                        const contentDiv = document.getElementById('content');
                                                                                                                                                            if (page === 'registerUnderwriter') {
                                                                                                                                                                    contentDiv.innerHTML = `
                                                                                                                                                                                <h2>Register Underwriter</h2>
                                                                                                                                                                                            <form onsubmit="registerUnderwriter(event)">
                                                                                                                                                                                                            <label for="name">Name:</label>
                                                                                                                                                                                                                            <input type="text" id="name" required>
                                                                                                                                                                                                                                            <label for="dob">DOB:</label>
                                                                                                                                                                                                                                                            <input type="date" id="dob" required>
                                                                                                                                                                                                                                                                            <label for="joiningDate">Joining Date:</label>
                                                                                                                                                                                                                                                                                            <input type="date" id="joiningDate" required>
                                                                                                                                                                                                                                                                                                            <label for="password">Password:</label>
                                                                                                                                                                                                                                                                                                                            <input type="password" id="password" required>
                                                                                                                                                                                                                                                                                                                                            <button type="submit">Register</button>
                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                    // Register Underwriter
                                                                                                                                                                                                                                                                                                                                                                    function registerUnderwriter(event) {
                                                                                                                                                                                                                                                                                                                                                                        event.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                            const underwriters = JSON.parse(localStorage.getItem('underwriters')) || [];
                                                                                                                                                                                                                                                                                                                                                                                const newUnderwriter = {
                                                                                                                                                                                                                                                                                                                                                                                        userId: 'UW' + (underwriters.length + 1),
                                                                                                                                                                                                                                                                                                                                                                                                name: document.getElementById('name').value,
                                                                                                                                                                                                                                                                                                                                                                                                        dob: document.getElementById('dob').value,
                                                                                                                                                                                                                                                                                                                                                                                                                joiningDate: document.getElementById('joiningDate').value,
                                                                                                                                                                                                                                                                                                                                                                                                                        password: document.getElementById('password').value
                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                underwriters.push(newUnderwriter);
                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('underwriters', JSON.stringify(underwriters));
                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('Underwriter Registered!');
                                                                                                                                                                                                                                                                                                                                                                                                                                        }